// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":return img`
2 2 2 2 2 2 2 2 
. . . 2 2 . . . 
. . . 2 2 . . . 
. . 2 . . 2 . . 
. 2 . . . . 2 . 
. 2 . . . . 2 . 
2 . . . . . . 2 
2 2 2 2 2 2 2 2 
`;
            case "image3":return img`
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
`;
            case "image4":return img`
c c c c c c c c 
b c c c c c c b 
c b b b b b b c 
c c c c c c c c 
b c c c c c c b 
c b b b b b b c 
c c c c c c c c 
c c c c c c c c 
`;
            case "image1":return img`
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
22222...............
.....2222222222.....
...............22222
....................
....................
....9...............
....9........2222222
fc..9.2222222.......
222222..............
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
